[package]
name = "explorator-plikow"
version = "0.1.0"
edition = "2024"

[dependencies]
eframe = { version = "0.22", features = ["default", "persistence"] }
egui = "0.22"
dirs = "5.0"
chrono = "0.4"
once_cell = "1.18"
parking_lot = "0.12"
human-sort = "0.2.2"
humansize = "2.1"
winapi = { version = "0.3", features = ["winuser", "windef", "libloaderapi"] }